### ISSUE TITLE
Formatting removes array brackets

### ISSUE THREAD

**Issue by buildwithsaurabhsuman** [petercaogx69/SQLFormatter#1]
Hi Team,

I was formatting SQL in IntelliJ and observed that the SQL started giving some exception after formatting.

**Issue:**
`postgress error SQL Error [42809]: ERROR: op ANY/ALL (array) requires array on right side_
`

Upon further checkup, I found that the formatter is removing [] from ARRAY method and hence the above error. My code sample for your reference:

**Code before formatting**
`s.synonym_type :: text = ANY(ARRAY ['TSA'::character varying, 'DUZ'::character varying, 'BCP'::character varying] :: text[])`

**Code after formatting**
`s.synonym_type :: text = ANY(ARRAY ['TSA'::character varying, 'DUZ'::character varying, 'BCP'::character varying] ::
text
)`

As shown above **text[]** changes to **text**

**Comment by petercaogx69** [comment]
Thanks for commit your issue, fixed, please try again

**Comment by petercaogx69** [comment]
fixed

**Comment by petercaogx69** [comment]
Hi Do you have any other question?
