### ISSUE TITLE
Errors happens when code contains: intersect, except

### ISSUE THREAD

**Issue by caoxuCarlos** [petercaogx69/SQLFormatter#2]
I was trying to format some sql code like:

SELECT * FROM A WHERE condition_a
INTERSECT
SELECT * FROM A WHERE condition_b
EXCEPT
SELECT * FROM A WHERE condition_c

It ends like:
SELECT * FROM A WHERE condition_c
SELECT * FROM A WHERE condition_c
SELECT * FROM A WHERE condition_c

**Comment by petercaogx69** [comment]
please give me a real SQL to me, Thanks.

**Comment by petercaogx69** [comment]
fixed

**Comment by petercaogx69** [comment]
你可以加我微信 petercaogx,有问题直接找我
