### ISSUE TITLE
关于注释

### ISSUE THREAD

**Issue by riruigit** [petercaogx69/SQLFormatter#3]
sql 中 # 的注释可以被保留，但是 -- 的注释为什么会被删除的，而且 没有找到 对应的入口设置

**Comment by petercaogx69** [comment]
把你的SQL发出来

**Comment by petercaogx69** [comment]
你最好使用/* … */这种形式的注释

**Comment by riruigit** [comment]
你好，这是我的sql语句

`-- 客户信息表
select t1.fid,
       -- 主-客户编码
       t1.fnumber,
       -- 主-中文名称
       t1.fname,
       -- 主-英文名称
       t1.fk_fhgk_englishname,
       -- 主-简称
       t1.fsimplename,
       -- 主-简码
       t1.fsimplepinyin,
       -- 主-客户所属系列
       t2.fname,
       -- 主-客户等级
       t1.fk_fhgk_customergrade,
       -- 主-客户背景
       t1.fk_fhgk_customerback,
       -- 主-业务职能
       t1.fbizfunction,
       -- 主-关联报备公司
       t1.fk_fhgk_affiliateddealer,
       -- 主-准入类型
       t1.fk_fhgk_admissiontype,
       -- 主-备注
       t1.fk_fhgk_remark,
       -- 主-创建组织名称
       t3.fname,
       -- 工商信息-地址
       t4.fname,
       -- 工商信息-省
       t5.fname,
       -- 工商信息-市
       t6.fname,
       -- 工商信息-区
       t7.fname,
       -- 工商信息-片区
       t1.fk_fhgk_area,
       -- 工商信息-客户主营产品
       t1.fk_fhgk_customermain,
       -- 工商信息-所属行业
       t8.fname,
       -- 销售信息-业务员姓名
       t9.ftruename,
       -- 销售信息-业务员厂卡号
       t9.fnumber,
       -- 销售信息-业务部
       t10.fname,
       -- 销售信息-内勤业务部
       t11.fname,
       -- 业务后勤信息-业务后勤
       t13.ftruename
from prd001_eip.t_bd_customer t1 # 关联客户系列
         left join prd001_eip.t_bas_assistantdataentry t2
                   on t1.fk_fhgk_assistantfield = t2.fentryid
-- 关联创建者组织名称
         left join prd001_eip.t_org_org t3 on t1.fcreateorgid = t3.fid
-- 关联所在地址, 这里带出省份 ， 市 ， 区的信息
         left join prd001_eip.t_cts_address t4 on t1.fk_fhgk_address = t4.fid
         left join prd001_eip.t_bd_admindivision t5 on t4.fadmindivisionid1 = t5.fid
         left join prd001_eip.t_bd_admindivision t6 on t4.fadmindivisionid2 = t6.fid
         left join prd001_eip.t_bd_admindivision t7 on t4.fadmindivisionid3 = t7.fid
         left join prd001_eip.t_bas_assistantdataentry t8 on t1.fk_fhgk_industrys = t8.fentryid
-- 关联人员信息，取出业务员
         left join prd001_eip.t_sec_user t9 on t1.fsalerid = t9.fid
-- 关联部门信息，获取部门名称
         left join prd001_eip.t_org_org t10 on t1.fsaledeptid = t10.fid
         left join prd001_eip.t_org_org t11 on t1.fk_fhgk_saledeptid = t11.fid
-- 业务后勤信息
         left join prd001_eip.tk_fhgk_logistics t12 on t1.fid = t12.fid and t12.fk_fhgk_status = 1
         left join prd001_eip.t_sec_user t13 on t12.fk_fhgk_logistics = t13.fid
where t1.fstatus = 'C'
  and t1.fenable = 1`

**Comment by riruigit** [comment]
我用插件进行格式化的时候，-- 开头的注释都被删除了。同时在 idea中使用 ctrl + r 把 -- 替换成 # 的注释，进行格式化的时候，把 select的字段都注释了。如图
<img width="400" alt="image" src="https://github.com/petercaogx69/SQLFormatter/assets/46668126/62ed3eed-bcd8-41b1-a9a2-54bbb71fef8b">

**Comment by petercaogx69** [comment]
已经提交了1.5.15版本，等待审批，请安装新版本再试试

**Comment by riruigit** [comment]
> 已经提交了1.5.15版本，等待审批，请安装新版本再试试
> 

好的。感谢你的付出。我看看新版本情况如何。

**Comment by petercaogx69** [comment]
/* 客户信息>表 */


SELECT
  t1.fid, -- 主 - 客户编码
  t1.fnumber, -- 主 - 中文名称
  t1.fname, -- 主 - 英文名称
  t1.fk_fhgk_englishname, -- 主 - 简称
  t1.fsimplename, -- 主 - 简码
  t1.fsimplepinyin, -- 主 - 客户所属系列
  t2.fname, -- 主 - 客户等级
  t1.fk_fhgk_customergrade, -- 主 - 客户等级
  t1.fk_fhgk_customerback, -- 主 - 客户背景
  t1.fbizfunction, -- 主 - 业务职能
  t1.fk_fhgk_affiliateddealer, -- 主 - 准入类型
  t1.fk_fhgk_admissiontype, -- 主 - 备注
  t1.fk_fhgk_remark, -- 主 - 创建组织名称
  t3.fname, -- 工商信息 - 地址
  t4.fname, -- 工商信息 - 省
  t5.fname, -- 工商信息 - 市
  t6.fname, -- 工商信息 - 区
  t7.fname, # 工商信息 - 片区
  t1.fk_fhgk_area, # 工商信息 - 客户主营产品
  t1.fk_fhgk_customermain, -- 工商信息 - 所属行业
  t8.fname, -- 销售信息 - 业务员姓 > 名
  t9.ftruename, -- 销售信息 - 业务员厂卡号
  t9.fnumber, -- 销售信息 - 业务部
  t10.fname, /* 销售信息 - 内勤业务部 */
  t11.fname, /* 业务后勤信息 - 业务后勤 */
  t13.ftruename
FROM
  prd001_eip.t_bd_customer t1 /* 关联客户系列 */
  LEFT JOIN prd001_eip.t_bas_assistantdataentry t2 ON t1.fk_fhgk_assistantfield = t2.fentryid -- 关联创建者组织名称
  LEFT JOIN prd001_eip.t_org_org t3 ON t1.fcreateorgid = t3.fid -- 关联所在地址, 这里带出省份 ， 市 ， 区的信息
  LEFT JOIN prd001_eip.t_cts_address t4 ON t1.fk_fhgk_address = t4.fid
  LEFT JOIN prd001_eip.t_bd_admindivision t5 ON t4.fadmindivisionid1 = t5.fid
  LEFT JOIN prd001_eip.t_bd_admindivision t6 ON t4.fadmindivisionid2 = t6.fid
  LEFT JOIN prd001_eip.t_bd_admindivision t7 ON t4.fadmindivisionid3 = t7.fid
  LEFT JOIN prd001_eip.t_bas_assistantdataentry t8 ON t1.fk_fhgk_industrys = t8.fentryid # 关联人员信息 ， 取出业务员
  LEFT JOIN prd001_eip.t_sec_user t9 ON t1.fsalerid = t9.fid -- > 关联部门信息 ， 获取部门名称
  LEFT JOIN prd001_eip.t_org_org t10 ON t1.fsaledeptid = t10.fid
  LEFT JOIN prd001_eip.t_org_org t11 ON t1.fk_fhgk_saledeptid = t11.fid # 业务后勤信息
  LEFT JOIN prd001_eip.tk_fhgk_logistics t12 ON t1.fid = t12.fid
    AND t12.fk_fhgk_status = 1
  LEFT JOIN prd001_eip.t_sec_user t13 ON t12.fk_fhgk_logistics = t13.fid
WHERE
  t1.fstatus = 'C'

**Comment by petercaogx69** [comment]
![图片](https://github.com/petercaogx69/SQLFormatter/assets/92414694/c6b2cb6f-b72d-4574-a136-95dffa7d61e9)

**Comment by petercaogx69** [comment]
增加了对各种注释方式的支持

**Comment by riruigit** [comment]
问题解决，感谢付出

**Comment by petercaogx69** [comment]
应该的，有什么请及时提出来

**Comment by petercaogx69** [comment]
能否麻烦您在Reviews里面给个好评，谢谢！！！

**Comment by riruigit** [comment]
好的，我看看怎么操作。

**Comment by petercaogx69** [comment]
petercaogx这是我微信，加我个微信，我们更方便沟通
